---
# tasks for install beats 
- name: install the latest version of Apache
  become: yes
  yum:
    name: libpcap
    state: latest

- name: standard install beat  packages
  become: yes
  yum: pkg={{ item }}
        state=present
  with_items:
      - https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.0.1-x86_64.rpm
      - https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.0.1-x86_64.rpm
      - https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-6.0.1-x86_64.rpm

- name: Start beats
  become: yes
  service: name={{ item }} state=started enabled=yes
  with_items:
      - filebeat
      - metricbeat
