---
# tasks for install beats 
- name: install the latest version of Apache
  become: yes
  yum:
    name: libpcap
    state: latest

- name: standard install beat  packages
  become: yes
  yum: pkg={{ item }}
        state=present
  with_items:
      - https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.6.4-x86_64.rpm
      - https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-5.6.4-x86_64.rpm
      - https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-5.6.4-x86_64.rpm

- name:  beat copy
  become: yes
  template: src={{ item }}.yml dest=/etc/{{ item }}/
  with_items:
      - filebeat
      - metricbeat
  notify: restart file beat
  notify: restart metric beat

- name: Start beats
  become: yes
  service: name={{ item }} state=started enabled=yes
  with_items:
      - filebeat
      - metricbeat
