--- 
 - name: Disable root login
   become: yes
   lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
   notify: restart sshd

 - name: Disable password authentication
   become: yes
   lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
   notify: restart sshd
