---
# tasks file for aws-create-ami
- name: Create AMI
  ec2_ami:
    region: "{{ region }}"
    instance_id: "{{ ec2_id }}"
    name: "{{ app_name }}-{{ app_version }}"
    wait: yes
    state: present
  register: ami

